# fly.toml app configuration file generated for mysql-icy-cherry-35 on 2024-09-15T14:37:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
# https://github.com/Tampereen-Urheilusukeltajat/Blenderi-Backend/blob/8a92a0d570eec38e3c4549d5aa93ffcfcafdd78c/infra/mariadb/fly.toml#L31

app = 'mysql-icy-cherry-35'
primary_region = 'ams'

[build]
  image = 'mysql:8.0.39-bookworm'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 3306
  protocol = 'tcp'
  processes = ["app"]
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  [[services.ports]]
    port = 3306
    handlers = ["pg_tls"]

[processes]
  app = """--datadir /data/mysql \
    --default-authentication-plugin mysql_native_password"""
  

[mounts]
  source = "mysqldata"
  destination = "/data"

[env]
  MYSQL_DATABASE = "some_db"
  MYSQL_USER = "non_root_user"